name: Check Code

on:
  push:
    branches:
      - '**'
      - '**'
  pull_request:
    branches:

jobs:
  checkcode:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout
      - name: Check py version
        uses: actions/setup-python
        with:
          python-version: '3.11.5'
      - name: Install dependencies
        run: |
          pip install pycodestyle
      - name: Run linter
        run: |
          pycodestyle .