name: Check Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkcode:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Clone repo
        uses: actions/checkout@v3

      # Шаг 2: Установка Python версии
      - name: Check Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      # Шаг 4: Запуск линтера
      - name: Run pycodestyle
        run: |
          pycodestyle . --exclude=venv,migrations --count --statistics
