name: Check Code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkcode:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 . --exclude venv,migrations --count --statistics