name: Check Code Style

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
jobs:
  checkcode:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Check python version
        uses: actions/setup-python
        with:
          python-versions: '3.11.5'

      - name: Install dependencies
        run: |
          pip install pycodestyle

      - name: Run linter
        run: |
          pycodestyle .
